FROM node:18-slim

# Install Poppler
RUN apt-get update && apt-get install -y poppler-utils

WORKDIR /app

# Copy backend package.json and install dependencies
COPY backend/package*.json ./
RUN npm install

# Copy backend files
COPY backend/ .

CMD ["node", "src/server.js"]
