[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Docker Compose settings
[plugins.docker-compose]
enabled = true
composeFilePath = "docker-compose.yml"
